# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Files/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(937, 775)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.url_list = QtWidgets.QListWidget(self.frame)
        self.url_list.setObjectName("url_list")
        self.horizontalLayout.addWidget(self.url_list)
        self.settings_panel = QtWidgets.QTabWidget(self.frame)
        self.settings_panel.setObjectName("settings_panel")
        self.video_selection = QtWidgets.QWidget()
        self.video_selection.setObjectName("video_selection")
        self.gridLayoutWidget = QtWidgets.QWidget(self.video_selection)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.age_limit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.age_limit.setObjectName("age_limit")
        self.gridLayout.addWidget(self.age_limit, 0, 3, 1, 1)
        self.min_views = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.min_views.setObjectName("min_views")
        self.gridLayout.addWidget(self.min_views, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.max_file_size = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.max_file_size.setObjectName("max_file_size")
        self.gridLayout.addWidget(self.max_file_size, 4, 3, 1, 1)
        self.max_views = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.max_views.setObjectName("max_views")
        self.gridLayout.addWidget(self.max_views, 2, 3, 1, 1)
        self.mine_file_size = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mine_file_size.setObjectName("mine_file_size")
        self.gridLayout.addWidget(self.mine_file_size, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.playlist_start = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.playlist_start.setObjectName("playlist_start")
        self.gridLayout.addWidget(self.playlist_start, 5, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 1, 1, 1)
        self.playlist_end = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.playlist_end.setObjectName("playlist_end")
        self.gridLayout.addWidget(self.playlist_end, 6, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setStatusTip("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 1, 1, 1)
        self.playlist_list = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.playlist_list.setObjectName("playlist_list")
        self.gridLayout.addWidget(self.playlist_list, 7, 3, 1, 1)
        self.settings_panel.addTab(self.video_selection, "")
        self.filesystem_options = QtWidgets.QWidget()
        self.filesystem_options.setObjectName("filesystem_options")
        self.settings_panel.addTab(self.filesystem_options, "")
        self.verbosity = QtWidgets.QWidget()
        self.verbosity.setObjectName("verbosity")
        self.settings_panel.addTab(self.verbosity, "")
        self.horizontalLayout.addWidget(self.settings_panel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.settings_panel.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qyoutube-dl"))
        self.label.setText(_translate("MainWindow", "Enter video URL:"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.label_5.setText(_translate("MainWindow", "Minimum files size:"))
        self.label_3.setText(_translate("MainWindow", "Minimum Views:"))
        self.label_2.setText(_translate("MainWindow", "Age Limit:"))
        self.label_4.setText(_translate("MainWindow", "Max Views:"))
        self.label_6.setText(_translate("MainWindow", "Maximum file size:"))
        self.label_7.setText(_translate("MainWindow", "Playlist start number:"))
        self.label_8.setText(_translate("MainWindow", "Playlist End:"))
        self.label_9.setText(_translate("MainWindow", "Playlist Items:"))
        self.settings_panel.setTabText(self.settings_panel.indexOf(self.video_selection), _translate("MainWindow", "Video Selection"))
        self.settings_panel.setTabText(self.settings_panel.indexOf(self.filesystem_options), _translate("MainWindow", "Filesystem Options"))
        self.settings_panel.setTabText(self.settings_panel.indexOf(self.verbosity), _translate("MainWindow", "Verbosity"))
        self.pushButton_2.setText(_translate("MainWindow", "Download Videos"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

