# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Files/settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(555, 638)
        SettingDialog.setMinimumSize(QtCore.QSize(555, 638))
        SettingDialog.setMaximumSize(QtCore.QSize(555, 638))
        self.tabWidget = QtWidgets.QTabWidget(SettingDialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 531, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 371, 21))
        self.label_3.setToolTip("")
        self.label_3.setObjectName("label_3")
        self.min_views = QtWidgets.QLineEdit(self.tab_3)
        self.min_views.setGeometry(QtCore.QRect(200, 40, 291, 20))
        self.min_views.setObjectName("min_views")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 371, 21))
        self.label_5.setToolTip("")
        self.label_5.setObjectName("label_5")
        self.age_limit = QtWidgets.QLineEdit(self.tab_3)
        self.age_limit.setGeometry(QtCore.QRect(200, 10, 291, 20))
        self.age_limit.setObjectName("age_limit")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 371, 21))
        self.label_4.setToolTip("")
        self.label_4.setObjectName("label_4")
        self.max_views = QtWidgets.QLineEdit(self.tab_3)
        self.max_views.setGeometry(QtCore.QRect(200, 70, 291, 20))
        self.max_views.setObjectName("max_views")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 100, 181, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 181, 16))
        self.label_2.setObjectName("label_2")
        self.min_file_size_text = QtWidgets.QLineEdit(self.tab_3)
        self.min_file_size_text.setGeometry(QtCore.QRect(200, 100, 291, 20))
        self.min_file_size_text.setObjectName("min_file_size_text")
        self.max_file_size_text = QtWidgets.QLineEdit(self.tab_3)
        self.max_file_size_text.setGeometry(QtCore.QRect(200, 130, 291, 20))
        self.max_file_size_text.setObjectName("max_file_size_text")
        self.playlist_start = QtWidgets.QLineEdit(self.tab_3)
        self.playlist_start.setGeometry(QtCore.QRect(200, 160, 291, 20))
        self.playlist_start.setObjectName("playlist_start")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 171, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 171, 21))
        self.label_8.setObjectName("label_8")
        self.playlist_end_number = QtWidgets.QLineEdit(self.tab_3)
        self.playlist_end_number.setGeometry(QtCore.QRect(200, 190, 291, 20))
        self.playlist_end_number.setObjectName("playlist_end_number")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.record_file = QtWidgets.QLineEdit(self.tab_4)
        self.record_file.setGeometry(QtCore.QRect(120, 10, 201, 20))
        self.record_file.setObjectName("record_file")
        self.select_record_file_button = QtWidgets.QPushButton(self.tab_4)
        self.select_record_file_button.setGeometry(QtCore.QRect(330, 10, 31, 21))
        self.select_record_file_button.setObjectName("select_record_file_button")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_6.setToolTip("")
        self.label_6.setObjectName("label_6")
        self.overwriteCheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.overwriteCheckBox.setGeometry(QtCore.QRect(10, 50, 481, 21))
        self.overwriteCheckBox.setObjectName("overwriteCheckBox")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.quietCheckBox = QtWidgets.QCheckBox(self.tab_5)
        self.quietCheckBox.setGeometry(QtCore.QRect(10, 10, 371, 18))
        self.quietCheckBox.setObjectName("quietCheckBox")
        self.ignoreCheckBox = QtWidgets.QCheckBox(self.tab_5)
        self.ignoreCheckBox.setGeometry(QtCore.QRect(10, 70, 371, 18))
        self.ignoreCheckBox.setObjectName("ignoreCheckBox")
        self.warningsCheckBox = QtWidgets.QCheckBox(self.tab_5)
        self.warningsCheckBox.setGeometry(QtCore.QRect(10, 50, 371, 18))
        self.warningsCheckBox.setObjectName("warningsCheckBox")
        self.verboseCheckBox = QtWidgets.QCheckBox(self.tab_5)
        self.verboseCheckBox.setGeometry(QtCore.QRect(10, 30, 371, 18))
        self.verboseCheckBox.setObjectName("verboseCheckBox")
        self.tabWidget.addTab(self.tab_5, "")
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(15, 590, 521, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(SettingDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(SettingDialog.close)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Settings"))
        self.label_3.setText(_translate("SettingDialog", "Age limit: "))
        self.label_5.setText(_translate("SettingDialog", "Maximum views: "))
        self.label_4.setText(_translate("SettingDialog", "Minimum views:"))
        self.label.setText(_translate("SettingDialog", "Minimum file size:"))
        self.label_2.setText(_translate("SettingDialog", "Maximum file size:"))
        self.label_7.setText(_translate("SettingDialog", "Playlist start number:"))
        self.label_8.setText(_translate("SettingDialog", "Playlist end number:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SettingDialog", "Video Selection"))
        self.select_record_file_button.setText(_translate("SettingDialog", "..."))
        self.label_6.setText(_translate("SettingDialog", "Save files to:"))
        self.overwriteCheckBox.setText(_translate("SettingDialog", "Prevent file overwrite"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("SettingDialog", "Filesystem Options"))
        self.quietCheckBox.setText(_translate("SettingDialog", "Quiet mode"))
        self.ignoreCheckBox.setText(_translate("SettingDialog", "Ignore errors"))
        self.warningsCheckBox.setText(_translate("SettingDialog", "No warnings"))
        self.verboseCheckBox.setText(_translate("SettingDialog", "Verbose Mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("SettingDialog", "Verbosity"))

